#!/usr/bin/bash

CURL="/usr/bin/curl"
HEADER_FILE="$0_curlheaders.txt"
HTTP_VERB="GET"
API_ENDPOINT="https://letsvalidate-webui-api.publicntp.workers.dev/api/v001/monitored-certificates"

${CURL} -i -X ${HTTP_VERB} -H @${HEADER_FILE} ${API_ENDPOINT}
